export const injuryMapping = {
      'Primary Assessment': {
        'A': 'Pulley injury grade I-II',
        'B': 'Pulley injury grade III-IV',
        'C': 'Flexor tenosynovitis',
        'D': 'FDP injury',
        'E': 'Lumbrical injury',
        'F': 'Joint capsulitis',
        'G': 'Collateral ligament injury',
        'H': 'Nerve issue',
        'I': 'Cyst',
        'J': 'Injury-induced pulley thickening',
        'K': 'Volar plate injury',
        'L': 'FDS insertional tendinopathy',
        'M': 'FDP insertional tendinopathy',
        'N': 'Lateral band syndrome',
      },
      'Differential Assessment 1': {
        'A': 'Pulley injury grade I-II',
        'B': 'Pulley injury grade III-IV',
        'C': 'Flexor tenosynovitis',
        'D': 'FDP injury',
        'E': 'Lumbrical injury',
        'F': 'Joint capsulitis',
        'G': 'Collateral ligament injury',
        'H': 'Nerve issue',
        'I': 'Cyst',
        'J': 'Injury-induced pulley thickening',
        'K': 'Volar plate injury',
        'L': 'FDS insertional tendinopathy',
        'M': 'FDP insertional tendinopathy',
        'N': 'Lateral band syndrome',
      }
    };
