export const injuryMapping = {
  'Primary Assessment': {
    'A': 'Pulley injury grade I-II',
    'B': 'Pulley injury grade III-IV',
    'C': 'Flexor tenosynovitis',
    'D': 'FDP injury',
    'E': 'Lumbrical injury',
    'F': 'Joint capsulitis',
    'G': 'Collateral ligament injury',
    'H': 'Nerve issue',
    'I': 'Cyst',
    'J': 'Injury-induced pulley thickening',
    'K': 'Volar plate injury',
    'L': 'FDS insertional tendinopathy',
    'M': 'FDP insertional tendinopathy',
    'N': 'Lateral band syndrome'
  },

  'Differential Assessment 1': {
    'A': 'Pulley injury grade I-II',
    'B': 'Pulley injury grade III-IV',
    'C': 'Flexor tenosynovitis',
    'D': 'FDP injury',
    'E': 'Lumbrical injury',
    'F': 'Joint capsulitis',
    'G': 'Collateral ligament injury',
    'H': 'Nerve issue',
    'I': 'Cyst',
    'J': 'Injury-induced pulley thickening',
    'K': 'Volar plate injury',
    'L': 'FDS insertional tendinopathy',
    'M': 'FDP insertional tendinopathy',
    'N': 'Lateral band syndrome'
  },

  'Differential Assessment 2': {
    'A': 'Pulley injury grade I-II',
    'B': 'Pulley injury grade III-IV',
    'C': 'Flexor tenosynovitis',
    'D': 'FDP injury',
    'E': 'Lumbrical injury',
    'F': 'Joint capsulitis',
    'G': 'Collateral ligament injury',
    'H': 'Nerve issue',
    'I': 'Cyst',
    'J': 'Injury-induced pulley thickening',
    'K': 'Volar plate injury',
    'L': 'FDS insertional tendinopathy',
    'M': 'FDP insertional tendinopathy',
    'N': 'Lateral band syndrome'
  },

  'Differential Assessment 3': {
    'A': 'Pulley injury grade I-II',
    'B': 'Pulley injury grade III-IV',
    'C': 'Flexor tenosynovitis',
    'D': 'FDP injury',
    'E': 'Lumbrical injury',
    'F': 'Joint capsulitis',
    'G': 'Collateral ligament injury',
    'H': 'Nerve issue',
    'I': 'Cyst',
    'J': 'Injury-induced pulley thickening',
    'K': 'Volar plate injury',
    'L': 'FDS insertional tendinopathy',
    'M': 'FDP insertional tendinopathy',
    'N': 'Lateral band syndrome'
  },

  'Differential Assessment 4': {
    'A': 'Pulley injury grade I-II',
    'B': 'Pulley injury grade III-IV',
    'C': 'Flexor tenosynovitis',
    'D': 'FDP injury',
    'E': 'Lumbrical injury',
    'F': 'Joint capsulitis',
    'G': 'Collateral ligament injury',
    'H': 'Nerve issue',
    'I': 'Cyst',
    'J': 'Injury-induced pulley thickening',
    'K': 'Volar plate injury',
    'L': 'FDS insertional tendinopathy',
    'M': 'FDP insertional tendinopathy',
    'N': 'Lateral band syndrome'
  },

  'Pulley Injury Severity Assessment': {
    'A': 'Grade I',
    'B': 'Grade II',
    'C': 'Grade III',
    'D': 'Grade IVa',
    'E': 'Grade IVb',
    'F': 'A2',
    'G': 'A3',
    'H': 'A4',
    'I': 'A2 + A3',
    'J': 'A3 + A4',
    'K': 'A2 + A3 + A4',
    'L': '',
    'M': '',
    'N': ''
  },

  'Joint Capsulitis Severity Assessment': {
    'A': 'Grade I',
    'B': 'Grade II',
    'C': 'Grade III',
    'D': '',
    'E': '',
    'F': '',
    'G': '',
    'H': '',
    'I': '',
    'J': '',
    'K': '',
    'L': '',
    'M': '',
    'N': ''
  },

  'FDP Injury Severity Assessment': {
    'A': 'Grade I',
    'B': 'Grade II',
    'C': 'Grade III',
    'D': '',
    'E': '',
    'F': '',
    'G': '',
    'H': '',
    'I': '',
    'J': '',
    'K': '',
    'L': '',
    'M': '',
    'N': ''
  },

  'Lumbrical Injury Severity Assessment': {
    'A': 'Grade I',
    'B': 'Grade II',
    'C': 'Grade III',
    'D': '',
    'E': '',
    'F': '',
    'G': '',
    'H': '',
    'I': '',
    'J': '',
    'K': '',
    'L': '',
    'M': '',
    'N': ''
  }
};
